$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: test-qa-env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ./conda.yml
description: Test environment for QA pipeline