name: Azure ML Deployment
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI
        run: az extension add -n ml

      - name: Register Data
        run: az ml data create --file data/dataset.yml --resource-group CASH-CLEARING --workspace-name cash-clearing-ai

      - name: Submit Job
        run: 
          az ml job create --file pipeline/train-pipeline.yml \
            --resource-group CASH-CLEARING \
            --workspace-name cash-clearing-ai

      - name: Set Schedule
        run: 
          az ml schedule create --file pipeline/schedule.yml \
            --resource-group CASH-CLEARING \
            --workspace-name cash-clearing-ai